package UTSSMT5.view;

// Import semua yang dibutuhkan
import UTSSMT5.model.Barang;
import UTSSMT5.service.BarangService;
import UTSSMT5.util.TableUtil;
import java.io.File;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager; // Ditambahkan untuk main method
import javax.swing.table.DefaultTableModel;
import javax.swing.filechooser.FileNameExtensionFilter; // <-- TAMBAHKAN IMPORT INI
/**
 * File: MainFrame.java
 * Tugas: VIEW - Menampilkan GUI dan menangani event.
 */
public class MainFrame extends javax.swing.JFrame {

    // --- KONEKSI KE CONTROLLER/SERVICE ---
    private final BarangService barangService;
    
    // --- Model untuk Komponen GUI ---
    private final DefaultListModel<String> kategoriListModel;
    private final DefaultTableModel barangTableModel;

    /**
     * Constructor
     */
    //Implementasi GUI menggunakan JFrame, JPanel, JList, JTable, JButton
    public MainFrame() {
        // INI PENTING: initComponents() HARUS DIPANGGIL PERTAMA
        initComponents(); 
        
        // 1. Buat Service (Controller)
        this.barangService = new BarangService();
        
        // 2. Siapkan model untuk JList Kategori
        this.kategoriListModel = new DefaultListModel<>();
        this.jListKategori.setModel(kategoriListModel);
        
        // 3. Siapkan model untuk JTable Barang
        this.barangTableModel = (DefaultTableModel) jTableBarang.getModel();
        
        // 4. Atur lebar kolom JTable (memanggil dari Util)
        TableUtil.setupTableColumns(jTableBarang);
        
        // 5. Muat data awal
        updateUI();
    }

    // --- METHOD HELPER (Logika internal untuk View) ---
    
    /**
     * Mengupdate SEMUA komponen UI (List dan Table)
     */
    private void updateUI() {
        updateKategoriList();
        
        // Otomatis pilih kategori pertama jika ada
        if (!kategoriListModel.isEmpty()) {
            jListKategori.setSelectedIndex(0);
        } else {
            // Jika tidak ada kategori, kosongkan tabel
            barangTableModel.setRowCount(0);
        }
        clearFields();
    }
    
    /**
     * Memperbarui daftar Kategori (JList)
     */
    private void updateKategoriList() {
        kategoriListModel.clear(); // Kosongkan list
        List<String> daftarKategori = barangService.getDaftarKategori();
        for (String kategori : daftarKategori) {
            kategoriListModel.addElement(kategori);
        }
    }
    
    /**
     * Memperbarui daftar Barang (JTable) berdasarkan kategori yang dipilih
     */
    private void updateBarangTable(String kategori) {
        if (kategori == null) {
            barangTableModel.setRowCount(0);
            return; 
        }
        
        List<Barang> daftarBarang = barangService.getBarangByKategori(kategori);
        TableUtil.updateBarangTable(barangTableModel, daftarBarang);
    }
    
    /**
     * Mengosongkan form "Detail Barang"
     */
    private void clearFields() {
        txtKode.setText("");
        txtNama.setText("");
        txtStok.setText("");
        txtHarga.setText("");
        jTableBarang.clearSelection(); // Hapus seleksi di tabel
        txtKode.setEnabled(true); // Aktifkan kembali field kode
        btnTambah.setEnabled(true); // Aktifkan tombol tambah
        btnEdit.setEnabled(false);  // Matikan tombol edit
        btnHapus.setEnabled(false); // Matikan tombol hapus
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKategori = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListKategori = new javax.swing.JList<>();
        panelTabel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBarang = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        panelDetail = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventori Barang");

        panelKategori.setBorder(javax.swing.BorderFactory.createTitledBorder("Kategori Barang"));

        jListKategori.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListKategori.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListKategoriValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListKategori);

        javax.swing.GroupLayout panelKategoriLayout = new javax.swing.GroupLayout(panelKategori);
        panelKategori.setLayout(panelKategoriLayout);
        panelKategoriLayout.setHorizontalGroup(
            panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelKategoriLayout.setVerticalGroup(
            panelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        panelTabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Stok", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBarang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableBarang.getTableHeader().setReorderingAllowed(false);
        jTableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBarang);
        if (jTableBarang.getColumnModel().getColumnCount() > 0) {
            jTableBarang.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableBarang.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableBarang.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTableBarang.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        btnTambah.setText("Tambah Barang");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Barang");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Barang");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnExport.setText("Export Data");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnImport.setText("Import Data");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImport, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabelLayout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addGap(27, 27, 27)
                        .addComponent(btnExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImport)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Barang"));

        jLabel5.setText("Kode Barang:");

        jLabel6.setText("Nama Barang:");

        jLabel7.setText("Stok:");

        jLabel8.setText("Harga:");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDetailLayout = new javax.swing.GroupLayout(panelDetail);
        panelDetail.setLayout(panelDetailLayout);
        panelDetailLayout.setHorizontalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKode, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtStok))
                .addGap(30, 30, 30)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama)
                    .addComponent(txtHarga))
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDetailLayout.setVerticalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // --- EVENT HANDLERS (Logika Tombol dan List) ---
    
    /**
     * EVENT: Dipicu saat KATEGORI di JList kiri diklik.
     */
    private void jListKategoriValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListKategoriValueChanged
        if (!evt.getValueIsAdjusting()) {
            String selectedKategori = jListKategori.getSelectedValue();
            updateBarangTable(selectedKategori);
            clearFields();
        }
    }//GEN-LAST:event_jListKategoriValueChanged

    /**
     * EVENT: Dipicu saat BARANG di JTable diklik.
     */
    //Fitur CRUD (Tambah, Edit, Hapus Barang)
    private void jTableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBarangMouseClicked
        int selectedRow = jTableBarang.getSelectedRow();
        if (selectedRow == -1) return; 
        
        String kode = barangTableModel.getValueAt(selectedRow, 0).toString();
        
        // Ambil data BARANG lengkap dari SERVICE
        Barang barang = barangService.getBarangByKode(kode);
        if (barang == null) return;
        
        // Masukkan data ke form detail
        txtKode.setText(barang.getKode());
        txtNama.setText(barang.getNama());
        txtStok.setText(String.valueOf(barang.getStok()));
        txtHarga.setText(String.valueOf(barang.getHarga())); // Angka murni
        
        // UX: Atur tombol
        txtKode.setEnabled(false);
        btnTambah.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_jTableBarangMouseClicked

    /**
     * EVENT: Tombol "Reset" diklik.
     */
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearFields();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * EVENT: Tombol "Tambah Barang" diklik.
     */
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            String kode = txtKode.getText().trim();
            String nama = txtNama.getText().trim();
            int stok = Integer.parseInt(txtStok.getText().trim());
            double harga = Double.parseDouble(txtHarga.getText().trim());
            String kategori = jListKategori.getSelectedValue();
            //Menampilkan daftar kategori menggunakan JList
            if (kode.isEmpty() || nama.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kode dan Nama tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (kategori == null) {
                JOptionPane.showMessageDialog(this, "Pilih Kategori terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (barangService.getBarangByKode(kode) != null) {
                 JOptionPane.showMessageDialog(this, "Kode Barang sudah ada!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Barang barangBaru = new Barang(kode, nama, stok, harga, kategori);
            barangService.tambahBarang(barangBaru);
            
            updateBarangTable(kategori); 
            clearFields();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stok harus angka dan Harga harus angka (contoh: 5500000)!", "Error Format", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * EVENT: Tombol "Edit Barang" diklik.
     */
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = jTableBarang.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih barang di tabel yang ingin di-edit!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String kode = txtKode.getText().trim(); // Kode (disabled)
            String nama = txtNama.getText().trim();
            int stok = Integer.parseInt(txtStok.getText().trim());
            double harga = Double.parseDouble(txtHarga.getText().trim());
            String kategori = jListKategori.getSelectedValue();
            
            if (nama.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Barang barangUpdate = new Barang(kode, nama, stok, harga, kategori);
            barangService.updateBarang(kode, barangUpdate);
            
            updateBarangTable(kategori);
            clearFields();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stok harus angka dan Harga harus angka (contoh: 5500000)!", "Error Format", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * EVENT: Tombol "Hapus Barang" diklik.
     */
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedRow = jTableBarang.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih barang di tabel yang ingin dihapus!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Menampilkan data barang dalam JTable
        String kode = txtKode.getText();
        String nama = txtNama.getText();
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Anda yakin ingin menghapus " + nama + " (Kode: " + kode + ")?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            barangService.hapusBarang(kode);
            updateBarangTable(jListKategori.getSelectedValue());
            clearFields();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * EVENT: Tombol "Export Data" diklik.
     */
    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
      JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Inventaris");
        
        // --- Buat Filter untuk setiap format ---
        FileNameExtensionFilter filterJson = new FileNameExtensionFilter("JSON file (*.json)", "json");
        FileNameExtensionFilter filterPdf = new FileNameExtensionFilter("PDF document (*.pdf)", "pdf");
        FileNameExtensionFilter filterXls = new FileNameExtensionFilter("Excel 97-2003 (*.xls)", "xls");
        
        // --- Tambahkan filter ke JFileChooser ---
        fileChooser.addChoosableFileFilter(filterJson);
        fileChooser.addChoosableFileFilter(filterPdf);
        fileChooser.addChoosableFileFilter(filterXls);
        
        // --- Set filter default (misalnya JSON) ---
        fileChooser.setFileFilter(filterJson);
        fileChooser.setSelectedFile(new File("inventaris.json")); // Nama default

        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            
            // Cek filter mana yang dipilih pengguna
            FileNameExtensionFilter selectedFilter = (FileNameExtensionFilter) fileChooser.getFileFilter();
            
            boolean success = false;
            String extension = "";

            if (selectedFilter == filterJson) {
                extension = ".json";
                // Pastikan file memiliki ekstensi .json
                if (!fileToSave.getName().toLowerCase().endsWith(extension)) {
                    fileToSave = new File(fileToSave.getAbsolutePath() + extension);
                }
                success = barangService.exportDataJSON(fileToSave); // Panggil method JSON
                
            } else if (selectedFilter == filterPdf) {
                extension = ".pdf";
                // Pastikan file memiliki ekstensi .pdf
                if (!fileToSave.getName().toLowerCase().endsWith(extension)) {
                    fileToSave = new File(fileToSave.getAbsolutePath() + extension);
                }
                success = barangService.exportDataPDF(fileToSave); // Panggil method PDF
                
            } else if (selectedFilter == filterXls) {
                extension = ".xls";
                // Pastikan file memiliki ekstensi .xls
                if (!fileToSave.getName().toLowerCase().endsWith(extension)) {
                    fileToSave = new File(fileToSave.getAbsolutePath() + extension);
                }
                success = barangService.exportDataXLS(fileToSave); // Panggil method XLS
            }

            // Tampilkan pesan hasil
            if (success) {
                JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke " + fileToSave.getName(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengekspor data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExportActionPerformed

    /**
     * EVENT: Tombol "Import Data" diklik.
     */
    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Buka Data Inventaris");
        
        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();
            if (barangService.importData(fileToOpen)) {
                updateUI(); // Update seluruh UI
                JOptionPane.showMessageDialog(this, "Data berhasil diimpor!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengimpor data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnImportActionPerformed


    /**
     * @param args the command line arguments
     */
     // MAIN METHOD INI SEKARANG TIDAK DIPERLUKAN KARENA ADA app.java
     // TAPI KITA BIARKAN SAJA AGAR BISA RUN FILE INI SENDIRI
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListKategori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBarang;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JPanel panelKategori;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}